import type { AdPackageDoc, ChannelDoc, ServiceDoc, TestimonialDoc } from './types'

/**
 * Sensible built-in content used when the CMS collections are still empty, so the
 * site always looks complete on a fresh install. Adding records in Payload
 * automatically replaces these.
 */

export const fallbackChannels: ChannelDoc[] = [
  {
    id: 'fallback-flagship',
    name: 'Latest Scoop',
    slug: 'latest-scoop',
    tagline: 'Mzansi celeb gossip, trends & the tea',
    handle: '@latestscoop000',
    channelId: process.env.YOUTUBE_CHANNEL_ID || 'UCGKAp6oM6s4GLTbYvtQeEoQ',
    url: 'https://www.youtube.com/@latestscoop000',
    shortDescription:
      'Serving you the latest in South African celeb gossip & trends — Amapiano stars, TV drama and the stories shaking Mzansi.',
    description:
      'Serving you the latest in South African celeb gossip & trends — Amapiano stars, TV drama and the stories shaking Mzansi.',
    subscriberCount: null,
    featured: true,
    order: 1,
    status: 'active',
    socials: [
      { platform: 'youtube', url: 'https://www.youtube.com/@latestscoop000' },
      { platform: 'instagram', url: 'https://www.instagram.com/' },
      { platform: 'tiktok', url: 'https://www.tiktok.com/' },
    ],
  },
]

export const fallbackServices: ServiceDoc[] = [
  {
    id: 'fallback-service-setup',
    title: 'YouTube Channel Setup',
    slug: 'youtube-channel-setup',
    icon: 'Rocket',
    category: 'channel-setup',
    summary: 'We set up your channel the right way — from channel art and About section to playlists and default upload settings.',
    order: 1,
    status: 'published',
    featured: true,
    price: 'From R1 500',
    ctaLabel: 'Start my channel',
    ctaHref: '/start-a-channel',
    features: [
      { title: 'Channel creation & verification', description: 'A professional, fully-optimised channel shell.' },
      { title: 'Branding & artwork', description: 'Profile picture, banner and watermark that fit your niche.' },
      { title: 'Playlists & channel sections', description: 'Organised so new viewers binge your best content.' },
      { title: 'Upload defaults & descriptions', description: 'Titles, tags and formatting templates you can reuse.' },
    ],
  },
  {
    id: 'fallback-service-niche',
    title: 'Niche Selection & Positioning',
    slug: 'niche-selection',
    icon: 'Compass',
    category: 'growth',
    summary: 'Find the exact niche, audience and angle that gives your channel the best chance of growing fast.',
    order: 2,
    status: 'published',
    features: [
      { title: 'Niche & sub-niche research', description: 'Pick a lane with demand and low competition.' },
      { title: 'Audience profile', description: 'Know exactly who you are making videos for.' },
      { title: 'Competitor breakdown', description: 'See what is working in your space — and where the gaps are.' },
    ],
  },
  {
    id: 'fallback-service-branding',
    title: 'Channel Branding & Artwork',
    slug: 'channel-branding',
    icon: 'Palette',
    category: 'branding',
    summary: 'A memorable visual identity — logo, colours, banner, thumbnails and templates that make you look established.',
    order: 3,
    status: 'published',
    features: [
      { title: 'Logo & colour system', description: 'A look you can use across YouTube and social.' },
      { title: 'Banner & channel art', description: 'Designed to fit every device.' },
      { title: 'Thumbnail templates', description: 'Reusable, on-brand templates you can edit yourself.' },
    ],
  },
  {
    id: 'fallback-service-content',
    title: 'Content Ideas & Planning',
    slug: 'content-ideas',
    icon: 'Lightbulb',
    category: 'content',
    summary: 'A month of video ideas mapped to titles, formats and an upload calendar you can actually stick to.',
    order: 4,
    status: 'published',
    features: [
      { title: 'Idea bank', description: '30+ video ideas tailored to your niche.' },
      { title: 'Content calendar', description: 'A realistic upload schedule.' },
      { title: 'Formats that work', description: 'Long-form, Shorts and community posts.' },
    ],
  },
  {
    id: 'fallback-service-shorts',
    title: 'Shorts Strategy',
    slug: 'shorts-strategy',
    icon: 'Clapperboard',
    category: 'content',
    summary: 'Turn long videos and raw ideas into a Shorts machine that brings new subscribers in every week.',
    order: 5,
    status: 'published',
    features: [
      { title: 'Shorts content plan', description: 'What to post and how often.' },
      { title: 'Hook & pacing coaching', description: 'Keep viewers watching to the end.' },
      { title: 'Repurposing workflow', description: 'Get more from every long video.' },
    ],
  },
  {
    id: 'fallback-service-thumbnails',
    title: 'Thumbnails & Titles',
    slug: 'thumbnails-and-titles',
    icon: 'Image',
    category: 'branding',
    summary: 'Higher click-through starts here. We craft and test titles and thumbnails that earn the click.',
    order: 6,
    status: 'published',
    features: [
      { title: 'Thumbnail design', description: 'Scroll-stopping, on-brand thumbnails.' },
      { title: 'Title frameworks', description: 'Titles that rank and get clicked.' },
      { title: 'A/B testing guidance', description: 'Use YouTube’s tools to improve results.' },
    ],
  },
  {
    id: 'fallback-service-analytics',
    title: 'Analytics & Growth Guidance',
    slug: 'analytics-guidance',
    icon: 'BarChart3',
    category: 'analytics',
    summary: 'Understand your data. We turn YouTube Analytics into clear, weekly actions that move the needle.',
    order: 7,
    status: 'published',
    features: [
      { title: 'Analytics walkthrough', description: 'Know which numbers matter.' },
      { title: 'Growth diagnosis', description: 'Why videos are (or aren’t) performing.' },
      { title: 'Action plan', description: 'A simple weekly routine to grow.' },
    ],
  },
  {
    id: 'fallback-service-monetization',
    title: 'Monetization Guidance',
    slug: 'monetization-guidance',
    icon: 'DollarSign',
    category: 'monetization',
    summary: 'From reaching 1,000 subscribers to unlocking AdSense, memberships and brand deals — build real income.',
    order: 8,
    status: 'published',
    features: [
      { title: 'AdSense & eligibility', description: 'Hit the requirements and apply with confidence.' },
      { title: 'Diversified income', description: 'Memberships, affiliates, products and sponsors.' },
      { title: 'Brand deal basics', description: 'Rates, media kits and negotiation.' },
    ],
  },
  {
    id: 'fallback-service-consulting',
    title: 'One-on-One Channel Consultations',
    slug: 'channel-consultations',
    icon: 'CalendarClock',
    category: 'consulting',
    summary: 'A focused strategy session with a channel audit, honest feedback and a personalised growth roadmap.',
    order: 9,
    status: 'published',
    featured: true,
    price: 'From R750 / session',
    ctaLabel: 'Book a consultation',
    ctaHref: '/contact',
    features: [
      { title: 'Channel audit', description: 'A review of your channel, videos and branding.' },
      { title: '90-minute session', description: 'Live over video call, with recording.' },
      { title: 'Action roadmap', description: 'A written plan you can start the same week.' },
    ],
  },
  {
    id: 'fallback-service-growth-partner',
    title: 'Ongoing Growth Partnership',
    slug: 'growth-partnership',
    icon: 'TrendingUp',
    category: 'growth',
    summary: 'A monthly retainer for creators who want a hands-on team handling strategy, thumbnails, titles and analytics.',
    order: 10,
    status: 'published',
    price: 'Custom quote',
    ctaLabel: 'Enquire about a retainer',
    ctaHref: '/contact',
    features: [
      { title: 'Monthly strategy call', description: 'Set targets and review progress.' },
      { title: 'Thumbnails & titles', description: 'Done-for-you, every upload.' },
      { title: 'Priority support', description: 'Direct line to our team.' },
    ],
  },
]

export const fallbackAdPackages: AdPackageDoc[] = [
  {
    id: 'fallback-ad-website',
    name: 'Website Spotlight',
    slug: 'website-spotlight',
    placement: 'website',
    summary: 'Reach our web audience with a branded placement across high-traffic pages and articles.',
    price: 'R2 500',
    billingPeriod: 'per month',
    order: 1,
    ctaLabel: 'Request a quote',
    ctaHref: '/advertise#enquiry',
    features: [
      { item: 'Banner placement on high-traffic pages' },
      { item: 'Sponsored blog article option' },
      { item: 'Monthly performance summary' },
    ],
  },
  {
    id: 'fallback-ad-youtube',
    name: 'YouTube Integration',
    slug: 'youtube-integration',
    placement: 'youtube',
    summary: 'A dedicated or integrated mention inside our videos, seen by an engaged South African audience.',
    price: 'From R4 500',
    billingPeriod: 'per video',
    order: 2,
    ctaLabel: 'Request a quote',
    ctaHref: '/advertise#enquiry',
    features: [
      { item: '30–60 second dedicated segment' },
      { item: 'Description links & pinned comment' },
      { item: 'Platform-native creative support' },
    ],
  },
  {
    id: 'fallback-ad-social',
    name: 'Social Media Campaign',
    slug: 'social-media-campaign',
    placement: 'social',
    summary: 'Multi-post campaigns across Instagram, TikTok and Facebook to extend your reach.',
    price: 'From R3 000',
    billingPeriod: 'per campaign',
    order: 3,
    ctaLabel: 'Request a quote',
    ctaHref: '/advertise#enquiry',
    features: [
      { item: 'Posts, reels and stories' },
      { item: 'Caption & hashtag strategy' },
      { item: 'Engagement report' },
    ],
  },
  {
    id: 'fallback-ad-bundle',
    name: 'Full Network Bundle',
    slug: 'full-network-bundle',
    placement: 'bundle',
    popular: true,
    summary: 'The complete campaign — YouTube, website and social — for maximum reach and frequency.',
    price: 'From R9 500',
    billingPeriod: 'per campaign',
    order: 4,
    ctaLabel: 'Plan my campaign',
    ctaHref: '/advertise#enquiry',
    features: [
      { item: 'YouTube dedicated segment' },
      { item: 'Website banner + article' },
      { item: 'Social media rollout' },
      { item: 'Consolidated campaign report' },
    ],
  },
]

export const fallbackTestimonials: TestimonialDoc[] = []
